[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
    "php83",                     # استخدم PHP 8.3 للاستقرار
    "php83Extensions.pdo_mysql", # السائق المطلوب
    "php83Extensions.mysqli"     # اختياري إذا تريد mysqli
]

[deploy]
startCommand = "frankenphp run"
healthcheckPath = "/check_driver.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
