[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
    "php",
    "php.pdo_mysql",
    "php.mysqli"
]

[deploy]
startCommand = "frankenphp run"
healthcheckPath = "/check_driver.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
